### ISSUE TITLE
Unable to generate readings/accents/etc. due to memory error.

### ISSUE THREAD

**Issue by rhodesmc** [migaku-official/Migaku-Japanese-Addon#58]
**Type:**
  - [X] bug
  - [ ] feature
  - [ ] enhancement
  - [ ] question

**Environment:**
  - OS: Windows 10 version 1903

**I'm going to open a PR to resolve the issue:**
  - [ ] yes
  - [X] no

**Description:**
Anki 2.1.22, with the JLPT Tango N5 Deck. Even trying to add to one field of one card slowly uses more and more memory until Anki gives a memory error (12 GB system RAM). Mass generation does not work either (same error). Mac OS version 10.12.6 with Anki 2.1.23 generates syntax, but readings, color, etc. do not display (only the syntax displays on cards). See below for error message.

Anki 2.1.22 (0ecc189a) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-06-24 19:54:08

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 31, in cmd
  File "aqt\webview.py", line 97, in _onCmd
  File "C:\Users\Michael and Max\AppData\Roaming\Anki2\addons21\278530045\main.py", line 386, in prevBridgeReroute
    ogAnkiWebBridge(self, cmd)
  File "aqt\webview.py", line 500, in _onBridgeCmd
  File "C:\Users\Michael and Max\AppData\Roaming\Anki2\addons21\278530045\main.py", line 310, in bridgeReroute
    mw.Exporter.finalizeGroupExport(self, splitList[1], field, self.note)
  File "C:\Users\Michael and Max\AppData\Roaming\Anki2\addons21\278530045\accentExporter.py", line 590, in finalizeGroupExport
    results = self.dictParser.getParsed(text)
  File "C:\Users\Michael and Max\AppData\Roaming\Anki2\addons21\278530045\accentExporter.py", line 64, in getParsed
    results = self.mecabAccents.accents(text)
  File "C:\Users\Michael and Max\AppData\Roaming\Anki2\addons21\278530045\reading.py", line 111, in accents
    final.append(results.replace('\r', '').replace('\n', ''))
MemoryError

**Comment by KieranMigaku** [comment]
Thank you for supporting Migaku.

We have closed this issue since this it is >6 months old; if you feel that this issue is still a problem in the latest version, please comment below and we will reopen and begin investigating this issue.

We apologise that recently we didn't have the manpower to maintain these repos properly, but we aim to maintain them better from here on out.
