### ISSUE TITLE
Anki start up and generating CSS and JS for Active Fields

### ISSUE THREAD

**Issue by GriefBacon** [migaku-official/Migaku-Japanese-Addon#78]
**Type:**
  - [X ] bug
  - [ ] feature
  - [ ] enhancement
  - [X ] question

**Environment:**
  - OS: Win 10

**I'm going to open a PR to resolve the issue:**
  - [ X] yes
  - [ ] no

**Description:**
Recently updated to the most stable version of anki and also updated the old MIA addons to the new Migaku versions. I have already uninstalled Migaku Japanese and reinstalled it but this did not solve my problem.

On start up: 
>エラー`  エラーが発生しました。Shiftキーを押した状態でAnkiを起動してください。この操作により、インストールされているアドオン全てが一時的に無効になります。  アドオン全てを無効にすると問題が起こらなくなる場合、メニューの[ツール]>[アドオン] でアドオン管理画面を開き、アドオンを１つまたはいくつか無効にしてAnkiを再起動してください。この手順を繰り返し、問題を引き起こすアドオンを特定してください。  問題を引き起こすアドオンを特定できた際は、その問題をサポートサイトのアドオンセクションにご報告いただければ幸いです。  Debug info: Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2 Platform: Windows 10 Flags: frz=True ao=True sv=1 Add-ons, last update check: 2021-03-07 10:06:22 Caught exception: Traceback (most recent call last):   File "aqt\main.py", line 286, in onOpenProfile   File "<C:\Users\RVRS\Anki\decorator.pyc:decorator-gen-30>", line 2, in loadProfile   File "anki\hooks.py", line 638, in decorator_wrapper   File "anki\hooks.py", line 633, in repl   File "aqt\main.py", line 427, in loadProfile   File "aqt\gui_hooks.py", line 2033, in __call__   File "anki\hooks.py", line 583, in runHook   File "C:\Users\RVRS\AppData\Roaming\Anki2\addons21\278530045\autoCSSJSHandling.py", line 92, in injectWrapperElements     self.mw.col.models.save(model)   File "anki\models.py", line 87, in save   File "anki\models.py", line 231, in update   File "anki\rsbackend_gen.py", line 414, in add_or_update_notetype   File "anki\rsbackend.py", line 267, in _run_command anki.rsbackend.TemplateError: Card template ⁨3⁩ has a problem. 

When I try to generate CSS and JS: 
>エラー  エラーが発生しました。Shiftキーを押した状態でAnkiを起動してください。この操作により、インストールされているアドオン全てが一時的に無効になります。  アドオン全てを無効にすると問題が起こらなくなる場合、メニューの[ツール]>[アドオン] でアドオン管理画面を開き、アドオンを１つまたはいくつか無効にしてAnkiを再起動してください。この手順を繰り返し、問題を引き起こすアドオンを特定してください。  問題を引き起こすアドオンを特定できた際は、その問題をサポートサイトのアドオンセクションにご報告いただければ幸いです。  Debug info: Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2 Platform: Windows 10 Flags: frz=True ao=True sv=1 Add-ons, last update check: 2021-03-07 10:06:22 Caught exception: Traceback (most recent call last):   File "C:\Users\RVRS\AppData\Roaming\Anki2\addons21\278530045\gui.py", line 609, in saveConfiguration     self.CSSJSHandler.injectWrapperElements(removeLegacy = removeLegacy)   File "C:\Users\RVRS\AppData\Roaming\Anki2\addons21\278530045\autoCSSJSHandling.py", line 92, in injectWrapperElements     self.mw.col.models.save(model)   File "anki\models.py", line 87, in save   File "anki\models.py", line 231, in update   File "anki\rsbackend_gen.py", line 414, in add_or_update_notetype   File "anki\rsbackend.py", line 267, in _run_command anki.rsbackend.TemplateError: Card template ⁨3⁩ has a problem.

**Comment by LucasMIA** [comment]
Send us your collection. This is an issue with one of your card templates though and doesn't appear to be an issue with the add-on.
